/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardFrontDeskIndexRouteImport } from './routes/dashboard/front-desk/index'
import { Route as DashboardManageRoomsIndexRouteImport } from './routes/dashboard/manage-rooms/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardReservationsIndexRouteImport } from './routes/dashboard/reservations/index'
import { Route as DashboardRoomsIndexRouteImport } from './routes/dashboard/rooms/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFrontDeskIndexRoute = DashboardFrontDeskIndexRouteImport.update({
  id: '/front-desk/',
  path: '/front-desk/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageRoomsIndexRoute =
  DashboardManageRoomsIndexRouteImport.update({
    id: '/manage-rooms/',
    path: '/manage-rooms/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReservationsIndexRoute =
  DashboardReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRoomsIndexRoute = DashboardRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/front-desk/': typeof DashboardFrontDeskIndexRoute
  '/dashboard/manage-rooms/': typeof DashboardManageRoomsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/reservations/': typeof DashboardReservationsIndexRoute
  '/dashboard/rooms/': typeof DashboardRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/front-desk': typeof DashboardFrontDeskIndexRoute
  '/dashboard/manage-rooms': typeof DashboardManageRoomsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/reservations': typeof DashboardReservationsIndexRoute
  '/dashboard/rooms': typeof DashboardRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/front-desk/': typeof DashboardFrontDeskIndexRoute
  '/dashboard/manage-rooms/': typeof DashboardManageRoomsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/reservations/': typeof DashboardReservationsIndexRoute
  '/dashboard/rooms/': typeof DashboardRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/front-desk/'
    | '/dashboard/manage-rooms/'
    | '/dashboard/reports/'
    | '/dashboard/reservations/'
    | '/dashboard/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/front-desk'
    | '/dashboard/manage-rooms'
    | '/dashboard/reports'
    | '/dashboard/reservations'
    | '/dashboard/rooms'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/front-desk/'
    | '/dashboard/manage-rooms/'
    | '/dashboard/reports/'
    | '/dashboard/reservations/'
    | '/dashboard/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/front-desk/': {
      id: '/dashboard/front-desk/'
      path: '/front-desk'
      fullPath: '/dashboard/front-desk/'
      preLoaderRoute: typeof DashboardFrontDeskIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage-rooms/': {
      id: '/dashboard/manage-rooms/'
      path: '/manage-rooms'
      fullPath: '/dashboard/manage-rooms/'
      preLoaderRoute: typeof DashboardManageRoomsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations/': {
      id: '/dashboard/reservations/'
      path: '/reservations'
      fullPath: '/dashboard/reservations/'
      preLoaderRoute: typeof DashboardReservationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rooms/': {
      id: '/dashboard/rooms/'
      path: '/rooms'
      fullPath: '/dashboard/rooms/'
      preLoaderRoute: typeof DashboardRoomsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFrontDeskIndexRoute: typeof DashboardFrontDeskIndexRoute
  DashboardManageRoomsIndexRoute: typeof DashboardManageRoomsIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardReservationsIndexRoute: typeof DashboardReservationsIndexRoute
  DashboardRoomsIndexRoute: typeof DashboardRoomsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFrontDeskIndexRoute: DashboardFrontDeskIndexRoute,
  DashboardManageRoomsIndexRoute: DashboardManageRoomsIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardReservationsIndexRoute: DashboardReservationsIndexRoute,
  DashboardRoomsIndexRoute: DashboardRoomsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
